In [2]:
import sys
import os

sys.path.append(os.path.abspath("/home/filippo/Github/Varational-Monte-Carlo/src/classes"))
sys.path.append(os.path.abspath("/home/filippo/Github/Varational-Monte-Carlo/src"))

import numpy as np
import Montecarlo
from scipy.differentiate import hessian
from functions import vector_module, Laplacian_op

In [3]:
x, y = np.array([1,2,3]), np.array([2,1,2])

print(vector_module(x-y))


1.7320508075688772


In [4]:
def testf(v):
    return v[0]**2 - v[0] + np.sin(v[1]) - v[2]

hess = hessian(testf, [1,2,4])

print(hess)

     success: [[ True False False]
               [False  True False]
               [False False False]]
      status: [[ 0 -1 -1]
               [-1  0 -1]
               [-1 -2 -2]]
       error: [[ 2.642e-14  4.230e-12  5.245e-12]
               [ 3.302e-13  2.976e-12  3.287e-13]
               [ 4.203e-11  7.199e-11  7.283e-12]]
        nfev: [[129 209 209]
               [143 121 143]
               [275 297 297]]
         ddf: [[ 2.000e+00 -4.217e-12  5.925e-12]
               [-3.349e-13 -9.093e-01 -3.228e-13]
               [-3.592e-11 -5.266e-11 -6.364e-12]]


In [5]:
v2 = np.array([[1,2,3,4],[2,1,4,5],[2,1,0,1]])
v2.shape

(3, 4)

In [6]:
hess2 = hessian(testf, v2)
hess2

     success: [[[ True  True  True  True]
                [False False False False]
                [ True False False False]]
              
               [[False False False False]
                [ True  True  True  True]
                [False False False False]]
              
               [[False False False False]
                [ True False False False]
                [False False False False]]]
      status: [[[ 0  0  0  0]
                [-1 -2 -1 -1]
                [ 0 -1 -1 -1]]
              
               [[-1 -1 -1 -1]
                [ 0  0  0  0]
                [-1 -1 -2 -1]]
              
               [[-1 -1 -1 -1]
                [ 0 -2 -1 -2]
                [-1 -1 -1 -1]]]
       error: [[[ 5.418e-14  1.017e-13  4.092e-13  3.051e-13]
                [ 3.159e-13  2.021e-11  5.103e-11  2.784e-12]
                [ 0.000e+00  3.285e-13  9.816e-13  1.073e-11]]
              
               [[ 3.176e-13  2.634e-12  5.322e-12  2.105e-11]
                [ 2.

In [7]:
hessdiag = np.diag(hess.ddf)
np.sum(hessdiag)

np.float64(1.0907025731676325)

In [8]:
Laplacian_op(testf, [1,2,4])

np.float64(1.0907025731676325)

In [9]:
np.linspace([-5.], [5.], 100)

array([[-5.        ],
       [-4.8989899 ],
       [-4.7979798 ],
       [-4.6969697 ],
       [-4.5959596 ],
       [-4.49494949],
       [-4.39393939],
       [-4.29292929],
       [-4.19191919],
       [-4.09090909],
       [-3.98989899],
       [-3.88888889],
       [-3.78787879],
       [-3.68686869],
       [-3.58585859],
       [-3.48484848],
       [-3.38383838],
       [-3.28282828],
       [-3.18181818],
       [-3.08080808],
       [-2.97979798],
       [-2.87878788],
       [-2.77777778],
       [-2.67676768],
       [-2.57575758],
       [-2.47474747],
       [-2.37373737],
       [-2.27272727],
       [-2.17171717],
       [-2.07070707],
       [-1.96969697],
       [-1.86868687],
       [-1.76767677],
       [-1.66666667],
       [-1.56565657],
       [-1.46464646],
       [-1.36363636],
       [-1.26262626],
       [-1.16161616],
       [-1.06060606],
       [-0.95959596],
       [-0.85858586],
       [-0.75757576],
       [-0.65656566],
       [-0.55555556],
       [-0

In [10]:
np.diagonal([[1.,2.,4.,2.],[1.,3.,4.,5.]])

array([1., 3.])

In [11]:
arr = np.array([[1,2,3],[3,4,5]])
print(arr)

print(arr.transpose())

[[1 2 3]
 [3 4 5]]
[[1 3]
 [2 4]
 [3 5]]


In [12]:
rng = np.random.default_rng()

dist = rng.standard_normal(1000)
print(dist)

[-7.84768480e-01 -7.21013510e-02  8.38339896e-01 -1.34731764e+00
 -6.65721615e-01  1.75625963e+00  2.60832664e-01 -1.10699112e+00
 -1.34698245e+00 -6.98042315e-01 -1.06167277e-01 -7.01359575e-01
 -7.24221844e-01 -1.02520427e+00 -2.27000682e-01 -1.28164789e+00
 -6.15944357e-01  1.08472549e+00  1.86723953e-01 -1.00590268e+00
  2.97633803e-01 -3.12796720e-01  8.81129902e-01 -7.18824511e-01
 -7.30061102e-01 -3.70854623e-01  2.39865021e-01  6.33599801e-01
  6.81407956e-01 -8.63749645e-01  2.18256918e-01  1.31927649e+00
 -6.65724533e-01 -7.19849708e-01  2.95664345e-01  8.49000512e-01
 -5.78313849e-02  3.30964387e-01 -9.37718630e-01 -7.48741984e-02
  1.33514801e+00 -1.32870485e+00 -2.95947119e-02 -2.98689569e-01
 -5.49530443e-01  4.09283053e-01 -8.28180385e-01  5.90134998e-01
 -2.67520129e-02 -2.59739955e-01  5.94676909e-01 -1.14084730e-01
  4.22869383e-01  1.01561744e+00  2.56918427e+00 -1.24583676e+00
  4.56787963e-01 -4.13810210e-01 -8.25594309e-02 -4.48559495e-01
  2.44753237e-02  2.04929