In [5]:
import sys
import os

sys.path.append(os.path.abspath("/home/filippo/Github/Varational-Monte-Carlo/src/classes"))

import numpy as np
import Montecarlo
from scipy.differentiate import hessian
import vector as vct

In [11]:
v = vct.Vector(x = 1, y = 3, z = 2)

print(v)

def testf(v):
    return v.x**2 - v.x + np.sin(v.y) - v.z



VectorObject3D(x=1, y=3, z=2)


In [19]:
a = np.zeros(1)
b = np.ones_like(a)

print(b)

for p,d in zip(a,b):
    print(p)
    print(d)


[1.]
0.0
1.0


In [61]:
def f(*args):
    print(args)

def g(f, *args):
    a = np.array(args, dtype=np.float64)
    print(tuple(a))
    f(tuple(a))

f(np.array([[1,2],[1,3]]), [1,2,3])
f([1,3,4])
g(f, [1,2,3], [1,3,4])

(array([[1, 2],
       [1, 3]]), [1, 2, 3])
([1, 3, 4],)
(array([1., 2., 3.]), array([1., 3., 4.]))
((array([1., 2., 3.]), array([1., 3., 4.])),)


In [58]:
r = [1,2,3],[1,3,4]
print(r)
arr = np.array(r)
b = tuple(arr)
print(b)

([1, 2, 3], [1, 3, 4])
(array([1, 2, 3]), array([1, 3, 4]))


In [68]:
print(*np.array([1,2]))

f(*[1,2,3])

1 2
(1, 2, 3)
