In [16]:
import sys
import os

sys.path.append(os.path.abspath("/home/filippo/Github/Varational-Monte-Carlo/src/classes"))
sys.path.append(os.path.abspath("/home/filippo/Github/Varational-Monte-Carlo/src"))

import numpy as np
import Montecarlo
from scipy.differentiate import hessian
from functions import vector_module, Laplacian_op

In [17]:
x, y = np.array([1,2,3]), np.array([2,1,2])

print(vector_module(x-y))


1.7320508075688772


In [18]:
def testf(v):
    return v[0]**2 - v[0] + np.sin(v[1]) - v[2]

hess = hessian(testf, [1,2,4])

print(hess)

     success: [[ True False False]
               [False  True False]
               [False False False]]
      status: [[ 0 -1 -1]
               [-1  0 -1]
               [-1 -2 -2]]
       error: [[ 2.642e-14  4.230e-12  5.245e-12]
               [ 3.302e-13  2.976e-12  3.287e-13]
               [ 4.203e-11  7.199e-11  7.283e-12]]
        nfev: [[129 209 209]
               [143 121 143]
               [275 297 297]]
         ddf: [[ 2.000e+00 -4.217e-12  5.925e-12]
               [-3.349e-13 -9.093e-01 -3.228e-13]
               [-3.592e-11 -5.266e-11 -6.364e-12]]


In [19]:
v2 = np.array([[1,2,3,4],[2,1,4,5],[2,1,0,1]])
v2.shape

(3, 4)

In [20]:
hess2 = hessian(testf, v2)
hess2

     success: [[[ True  True  True  True]
                [False False False False]
                [ True False False False]]
              
               [[False False False False]
                [ True  True  True  True]
                [False False False False]]
              
               [[False False False False]
                [ True False False False]
                [False False False False]]]
      status: [[[ 0  0  0  0]
                [-1 -2 -1 -1]
                [ 0 -1 -1 -1]]
              
               [[-1 -1 -1 -1]
                [ 0  0  0  0]
                [-1 -1 -2 -1]]
              
               [[-1 -1 -1 -1]
                [ 0 -2 -1 -2]
                [-1 -1 -1 -1]]]
       error: [[[ 5.418e-14  1.017e-13  4.092e-13  3.051e-13]
                [ 3.159e-13  2.021e-11  5.103e-11  2.784e-12]
                [ 0.000e+00  3.285e-13  9.816e-13  1.073e-11]]
              
               [[ 3.176e-13  2.634e-12  5.322e-12  2.105e-11]
                [ 2.

In [21]:
hessdiag = np.diag(hess.ddf)
np.sum(hessdiag)

np.float64(1.0907025731676325)

In [22]:
Laplacian_op(testf, [1,2,4])

np.float64(1.0907025731676325)

In [23]:
np.linspace([-5.], [5.], 100)

array([[-5.        ],
       [-4.8989899 ],
       [-4.7979798 ],
       [-4.6969697 ],
       [-4.5959596 ],
       [-4.49494949],
       [-4.39393939],
       [-4.29292929],
       [-4.19191919],
       [-4.09090909],
       [-3.98989899],
       [-3.88888889],
       [-3.78787879],
       [-3.68686869],
       [-3.58585859],
       [-3.48484848],
       [-3.38383838],
       [-3.28282828],
       [-3.18181818],
       [-3.08080808],
       [-2.97979798],
       [-2.87878788],
       [-2.77777778],
       [-2.67676768],
       [-2.57575758],
       [-2.47474747],
       [-2.37373737],
       [-2.27272727],
       [-2.17171717],
       [-2.07070707],
       [-1.96969697],
       [-1.86868687],
       [-1.76767677],
       [-1.66666667],
       [-1.56565657],
       [-1.46464646],
       [-1.36363636],
       [-1.26262626],
       [-1.16161616],
       [-1.06060606],
       [-0.95959596],
       [-0.85858586],
       [-0.75757576],
       [-0.65656566],
       [-0.55555556],
       [-0

In [24]:
np.diagonal([[1.,2.,4.,2.],[1.,3.,4.,5.]])

array([1., 3.])

In [25]:
arr = np.array([[1,2,3],[3,4,5]])
print(arr)

print(arr.transpose())

[[1 2 3]
 [3 4 5]]
[[1 3]
 [2 4]
 [3 5]]


In [26]:
rng = np.random.default_rng()

dist = rng.standard_normal(1000)
print(dist)

[-7.33082633e-01 -3.35837808e-01  2.51868996e+00  1.44951971e-01
  9.53012361e-01  2.53051413e-01 -6.89283506e-01 -6.06347018e-01
 -1.88620877e+00  3.74710210e-01  1.09663264e+00 -3.61504518e-01
  1.50026552e+00  6.23909694e-01 -3.13839879e+00  9.09918019e-01
 -1.07909064e+00  1.65138411e-01  1.07187554e+00  9.39630713e-01
 -7.18743805e-01 -9.20272250e-01 -1.38802715e+00 -8.32517059e-01
 -1.57139505e+00  1.02708337e+00 -9.57773741e-02  2.24409651e-01
  2.25935758e-01  4.27310535e-01  1.16842091e-01 -4.09862909e-01
 -9.94793017e-01  8.43324595e-01 -4.80310864e-01 -1.09892672e+00
 -1.65927692e-01 -2.20057680e+00  8.92122514e-02 -2.71150803e-01
 -8.74494989e-01 -8.76888286e-01 -1.02458587e+00 -3.22811476e-01
  4.83916835e-01 -1.40871376e+00  4.06184494e-01  2.44454342e+00
 -7.44039879e-01 -8.43882097e-01 -1.09171501e+00  4.21134978e-01
 -1.14608412e+00  7.27703166e-01  6.54383412e-01  3.80491766e-01
 -5.28405713e-01  5.65335643e-01  1.59874686e-01 -5.50117133e-01
 -1.18225240e+00  8.45529

In [27]:
foo = [np.array([22], dtype = float)]

print(foo)

np.sqrt(foo)

[array([22.])]


array([[4.69041576]])